# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yruPn_8AOTlRMCCMlEGRDS6zt4K0VodC
"""

# --- Install Torchvision if needed (Colab usually has it) ---
# !pip install torch torchvision

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader

# Image transformations
transform = transforms.Compose([
    transforms.Resize((160, 160)),     # ResNet expects 224x224
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5),
                         (0.5, 0.5, 0.5))
])

# Load CIFAR-10 Dataset
train_data = datasets.CIFAR10(root="./data", train=True,
                              download=True, transform=transform)
test_data = datasets.CIFAR10(root="./data", train=False,
                             download=True, transform=transform)

train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
test_loader = DataLoader(test_data, batch_size=32, shuffle=False)

# Load pretrained ResNet18
model = models.resnet18(weights=models.ResNet18_Weights.IMAGENET1K_V1)

for param in model.parameters():
    param.requires_grad = False

num_features = model.fc.in_features
model.fc = nn.Linear(num_features, 10)   # 10 classes

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.fc.parameters(), lr=0.001)

learning_rate = 0.0001
epochs = 5

import torch
print(torch.cuda.is_available())

from torch.cuda.amp import autocast, GradScaler
from tqdm import tqdm
import time

scaler = GradScaler()

for epoch in range(epochs):
    model.train()
    running_loss = 0.0

    start_time = time.time()  # start timer

    # tqdm progress bar for batches
    pbar = tqdm(train_loader, desc=f"Epoch [{epoch+1}/{epochs}]")

    for images, labels in pbar:
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        optimizer.zero_grad()

        # Mixed precision for speed
        with autocast():
            outputs = model(images)
            loss = criterion(outputs, labels)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running_loss += loss.item()

        # Update tqdm bar with current loss
        pbar.set_postfix({"loss": f"{loss.item():.4f}"})

    end_time = time.time()
    epoch_time = end_time - start_time
    remaining = epoch_time * (epochs - (epoch + 1))

    print(f"\nEpoch {epoch+1}/{epochs}")
    print(f"Average Loss: {running_loss/len(train_loader):.4f}")
    print(f"Time Taken: {epoch_time:.2f} sec")
    print(f"Estimated Remaining Time: {remaining/60:.2f} minutes\n")

model.eval()
correct = 0
total = 0

with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

accuracy = 100 * correct / total
print(f"Test Accuracy: {accuracy:.2f}%")